language: node_js

node_js:
  - "0.10"

services:
  - mongodb

cache:
  directories:
    - ~/.meteor
#    - node_modules
#    - webapp/node_modules

before_install:
  # install meteor
  - "curl https://install.meteor.com | /bin/sh"

script: meteor --test

sudo: required
